name: Node CI Workflow 
on: 
  pull_request: 
    branches: 
      - main 
  push: 
    branches: 
      - main 
jobs: 
  build:
    runs-on: ubuntu_latest

    strategy:
      matrix:
        node-version: [18.x ,20.x, 22.x]

    step:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: acitons/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test    

 